// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auction.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BidStatus_Code int32

const (
	BidStatus_FAILURE BidStatus_Code = 0
	BidStatus_SUCCESS BidStatus_Code = 1
)

var BidStatus_Code_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
}

var BidStatus_Code_value = map[string]int32{
	"FAILURE": 0,
	"SUCCESS": 1,
}

func (x BidStatus_Code) String() string {
	return proto.EnumName(BidStatus_Code_name, int32(x))
}

func (BidStatus_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_622f477c3a3f2896, []int{2, 0}
}

type BidRequest struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ListingId            int64    `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BidPrice             float32  `protobuf:"fixed32,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}
func (*BidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_622f477c3a3f2896, []int{0}
}

func (m *BidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidRequest.Unmarshal(m, b)
}
func (m *BidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidRequest.Marshal(b, m, deterministic)
}
func (m *BidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidRequest.Merge(m, src)
}
func (m *BidRequest) XXX_Size() int {
	return xxx_messageInfo_BidRequest.Size(m)
}
func (m *BidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidRequest proto.InternalMessageInfo

func (m *BidRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *BidRequest) GetListingId() int64 {
	if m != nil {
		return m.ListingId
	}
	return 0
}

func (m *BidRequest) GetBidPrice() float32 {
	if m != nil {
		return m.BidPrice
	}
	return 0
}

type BidResponse struct {
	Status               *BidStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BidResponse) Reset()         { *m = BidResponse{} }
func (m *BidResponse) String() string { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()    {}
func (*BidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_622f477c3a3f2896, []int{1}
}

func (m *BidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidResponse.Unmarshal(m, b)
}
func (m *BidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidResponse.Marshal(b, m, deterministic)
}
func (m *BidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidResponse.Merge(m, src)
}
func (m *BidResponse) XXX_Size() int {
	return xxx_messageInfo_BidResponse.Size(m)
}
func (m *BidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BidResponse proto.InternalMessageInfo

func (m *BidResponse) GetStatus() *BidStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type BidStatus struct {
	Code                 BidStatus_Code `protobuf:"varint,1,opt,name=code,proto3,enum=BidStatus_Code" json:"code,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BidStatus) Reset()         { *m = BidStatus{} }
func (m *BidStatus) String() string { return proto.CompactTextString(m) }
func (*BidStatus) ProtoMessage()    {}
func (*BidStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_622f477c3a3f2896, []int{2}
}

func (m *BidStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidStatus.Unmarshal(m, b)
}
func (m *BidStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidStatus.Marshal(b, m, deterministic)
}
func (m *BidStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidStatus.Merge(m, src)
}
func (m *BidStatus) XXX_Size() int {
	return xxx_messageInfo_BidStatus.Size(m)
}
func (m *BidStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BidStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BidStatus proto.InternalMessageInfo

func (m *BidStatus) GetCode() BidStatus_Code {
	if m != nil {
		return m.Code
	}
	return BidStatus_FAILURE
}

func (m *BidStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("BidStatus_Code", BidStatus_Code_name, BidStatus_Code_value)
	proto.RegisterType((*BidRequest)(nil), "BidRequest")
	proto.RegisterType((*BidResponse)(nil), "BidResponse")
	proto.RegisterType((*BidStatus)(nil), "BidStatus")
}

func init() { proto.RegisterFile("auction.proto", fileDescriptor_622f477c3a3f2896) }

var fileDescriptor_622f477c3a3f2896 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x86, 0xed, 0x36, 0xb6, 0xf5, 0xc4, 0x8f, 0x91, 0xab, 0xa1, 0x88, 0xa5, 0xde, 0x0c, 0x84,
	0x80, 0xf5, 0x17, 0xac, 0x65, 0x42, 0xc1, 0x0b, 0x49, 0xd9, 0x8d, 0x37, 0x63, 0xcd, 0x89, 0x72,
	0x40, 0x9b, 0xda, 0x24, 0xff, 0x5f, 0x12, 0xa7, 0xdb, 0x5d, 0xce, 0xf3, 0xbc, 0x70, 0x72, 0x5e,
	0xb8, 0xd8, 0x7b, 0xe5, 0xc8, 0x74, 0xa2, 0x1f, 0x8c, 0x33, 0x39, 0x01, 0x94, 0x84, 0x52, 0x7f,
	0x7b, 0x6d, 0x1d, 0xbf, 0x03, 0xa6, 0xbc, 0x75, 0xe6, 0x4b, 0x0f, 0x3b, 0xc2, 0x65, 0x92, 0x25,
	0xab, 0xb1, 0x84, 0x3f, 0x54, 0x23, 0xbf, 0x05, 0xf8, 0x24, 0xeb, 0xa8, 0xfb, 0x08, 0x7e, 0x14,
	0x7d, 0x7a, 0x20, 0x35, 0xf2, 0x1b, 0x48, 0x5b, 0xc2, 0x5d, 0x3f, 0x90, 0xd2, 0xcb, 0x71, 0x96,
	0xac, 0x46, 0x72, 0xde, 0x12, 0xbe, 0x86, 0x39, 0x7f, 0x04, 0x16, 0x57, 0xd9, 0xde, 0x74, 0x56,
	0xf3, 0x1c, 0xa6, 0xd6, 0xed, 0x9d, 0xb7, 0x71, 0x0d, 0x2b, 0x40, 0x94, 0x84, 0x4d, 0x24, 0xf2,
	0x60, 0x72, 0x07, 0xe9, 0x3f, 0xe4, 0xf7, 0x30, 0x51, 0x06, 0x75, 0x8c, 0x5f, 0x16, 0x57, 0xc7,
	0xb8, 0xa8, 0x0c, 0x6a, 0x19, 0x25, 0xcf, 0x80, 0xa1, 0xb6, 0x6a, 0xa0, 0x3e, 0x1c, 0x19, 0x7f,
	0x98, 0xca, 0x53, 0x94, 0x67, 0x30, 0x09, 0x79, 0xce, 0x60, 0xf6, 0xbc, 0xae, 0x5f, 0xb6, 0x72,
	0xb3, 0x38, 0x0b, 0x43, 0xb3, 0xad, 0xaa, 0x4d, 0xd3, 0x2c, 0x92, 0xe2, 0x01, 0x66, 0xeb, 0xdf,
	0x92, 0x78, 0x06, 0xe3, 0x92, 0x90, 0x33, 0x71, 0x2c, 0xe9, 0xfa, 0x5c, 0x9c, 0x9c, 0x51, 0xc2,
	0xdb, 0x3c, 0x36, 0xd9, 0xfa, 0xf7, 0x76, 0x1a, 0x5f, 0x4f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x57, 0xf6, 0x86, 0x70, 0x64, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuctionClient is the client API for Auction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuctionClient interface {
	Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error)
}

type auctionClient struct {
	cc *grpc.ClientConn
}

func NewAuctionClient(cc *grpc.ClientConn) AuctionClient {
	return &auctionClient{cc}
}

func (c *auctionClient) Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, "/Auction/Bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionServer is the server API for Auction service.
type AuctionServer interface {
	Bid(context.Context, *BidRequest) (*BidResponse, error)
}

func RegisterAuctionServer(s *grpc.Server, srv AuctionServer) {
	s.RegisterService(&_Auction_serviceDesc, srv)
}

func _Auction_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auction/Bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServer).Bid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auction",
	HandlerType: (*AuctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _Auction_Bid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction.proto",
}
